/* The no-fees rule (R7, A-51) on a fixed corpus of realistic listing lines, gathered by the Stage 4 fix reviews: a legitimate line (stated pay, a benefit,
   a duty, an anti-scam or negated notice) is never refused, and a demand that the candidate pay is refused or at least flagged for the reviewer.
   A change to the fee wording that undoes an earlier round's case fails here (fix review 7). Add a line when a new case is found; never remove one. */
import { test } from "node:test";
import assert from "node:assert/strict";
import { loadCore } from "../server/core.js";
import { sanitizeJob, checkJob } from "../server/validate.js";

const core = loadCore(), base = { title: { en: "Storekeeper" }, gov: "aleppo", type: "full", level: "entry", pay: [1800000, 2200000], langs: ["ar"], summary: { en: "Keep the stock records." } };
const outcome = ([box, lang, line]) => { const r = checkJob(core, sanitizeJob(core, { ...base, [box]: box === "summary" ? { [lang]: line } : { [lang]: [line] } })); return r.fee ? "refused" : r.flags.some(f => f.type === "fee") ? "flagged" : "silent"; };

const LEGIT = [
  ["provides", "en", "Intern pay 400,000 SYP per month"],
  ["provides", "en", "Monthly stipend of 300,000 SYP for every trainee"],
  ["provides", "en", "Trainees are paid 250,000 SYP monthly"],
  ["provides", "en", "The company pays for transportation"],
  ["provides", "en", "We pay social insurance for all employees"],
  ["provides", "en", "Health insurance fully paid by the company"],
  ["provides", "en", "Tuition fees covered for further study"],
  ["provides", "en", "Paid annual leave of 14 days"],
  ["provides", "en", "Salary paid on the 1st of every month"],
  ["provides", "en", "Student pay 250,000 SYP per month"],
  ["provides", "en", "Interns will be paid 300,000 SYP"],
  ["provides", "en", "Transport allowance: 100,000 SYP"],
  ["provides", "en", "Students who complete the program will be paid a bonus of 200 USD"],
  ["provides", "en", "Free lunch, and we pay your internet bill"],
  ["provides", "en", "Trainee pay is 300,000 SYP, paid monthly"],
  ["provides", "en", "Each intern gets a 200 USD monthly allowance"],
  ["provides", "en", "We cover the trainee's transport; trainees pay nothing"],
  ["provides", "en", "Internship pay: 350,000 SYP; applicants pay nothing"],
  ["provides", "en", "Apprentice pay 300,000 SYP"],
  ["provides", "en", "Overtime is paid at 1.5x"],
  ["duties", "en", "Process customer payments and issue receipts"],
  ["duties", "en", "Pay suppliers on time and reconcile accounts"],
  ["duties", "en", "You will pay close attention to detail"],
  ["duties", "en", "Prepare payroll and pay employees' salaries"],
  ["duties", "en", "Handle the cash register and receive payments of up to 5 million SYP a day"],
  ["duties", "en", "Follow up on overdue invoices and make sure clients pay on time"],
  ["duties", "en", "Record student payments in the accounting system"],
  ["needs", "en", "Candidates must have 2 years of experience"],
  ["needs", "en", "Applicants should be able to work under pressure"],
  ["needs", "en", "The candidate will be paid according to experience"],
  ["provides", "en", "No candidate pays a fee"],
  ["provides", "en", "No deposit required"],
  ["provides", "en", "No applicant will pay a deposit"],
  ["summary", "en", "Applications are free. We will never ask you to pay anything."],
  ["summary", "en", "Candidates do not pay anything at any stage."],
  ["provides", "en", "No need to pay to apply"],
  ["provides", "en", "Candidates will never pay anything"],
  ["summary", "en", "Trainees will pay attention to safety rules at all times."],
  ["provides", "en", "Candidates never have to pay; beware of anyone asking for money"],
  ["provides", "ar", "مكافأة المتدرب تُدفع شهرياً"],
  ["provides", "ar", "مكافأة شهرية للمتدرب ٣٠٠ ألف ليرة"],
  ["provides", "ar", "تدفع الشركة بدل المواصلات"],
  ["provides", "ar", "تتحمل الشركة رسوم التسجيل في النقابة"],
  ["provides", "ar", "دفع رسوم النقابة على حساب الشركة"],
  ["provides", "ar", "تأمين صحي على حساب الشركة"],
  ["provides", "ar", "الراتب يُدفع في أول كل شهر"],
  ["provides", "ar", "يتم دفع الراتب ١٫٥ مليون ليرة شهرياً"],
  ["provides", "ar", "بدل مواصلات ١٠٠ ألف ليرة"],
  ["provides", "ar", "تدفع الشركة للمتدربين مكافأة ٢٠٠ ألف ليرة شهرياً"],
  ["summary", "ar", "يتقاضى المتدرب مكافأة شهرية قدرها ٢٠٠ ألف ليرة"],
  ["provides", "ar", "المتدرب يتقاضى ٣٠٠ ألف ليرة"],
  ["provides", "ar", "يُدفع للمتدرب ٤٠٠ ألف ليرة شهرياً"],
  ["provides", "ar", "مكافأة المتدرب تدفع ٤٠٠ ألف ليرة شهرياً"],
  ["provides", "ar", "مكافأة المتدرب: ٤٠٠ ألف ليرة، تدفع شهرياً"],
  ["provides", "ar", "نتكفل بدفع رسوم الدورات التدريبية"],
  ["provides", "ar", "فرصة تدريب مدفوعة الأجر"],
  ["provides", "ar", "وتدفع الشركة كامل تكاليف السكن"],
  ["provides", "ar", "وتتحمل الشركة تكاليف التدريب والسكن"],
  ["provides", "ar", "تدريب مدفوع، والشركة تتحمل التكاليف"],
  ["duties", "ar", "استلام الدفعات من الزبائن وتسجيلها"],
  ["duties", "ar", "تسديد فواتير الموردين ومتابعة الحسابات"],
  ["duties", "ar", "متابعة تحصيل المبالغ المستحقة من العملاء"],
  ["duties", "ar", "دفع رواتب الموظفين وإعداد كشوف الرواتب"],
  ["duties", "ar", "مسؤول عن تسديد الدفعات للموردين"],
  ["duties", "ar", "متابعة دفع الأقساط من الطلاب وتسجيلها"],
  ["duties", "ar", "تحصيل الأقساط من الطلاب وتسديدها للإدارة"],
  ["duties", "ar", "تدريب المتدربين ومتابعة أدائهم"],
  ["duties", "ar", "وتسديد الذمم المستحقة على الشركة"],
  ["summary", "ar", "التقديم مجاني ولا يدفع المتقدم أي مبلغ"],
  ["summary", "ar", "نرجو من المتقدمين عدم دفع أي مبلغ لأي جهة"],
  ["summary", "ar", "لا تطلب الشركة من المتقدمين دفع أي مبلغ"],
  ["summary", "ar", "تنبيه: الشركة لا تطلب من المتقدمين دفع أي مبلغ مقابل التوظيف"],
  ["summary", "ar", "التدريب مجاني بالكامل، ولا يتحمل المتدرب أي تكاليف"],
  ["summary", "ar", "ليس على المتقدم دفع أي مبلغ"],
  ["summary", "ar", "لا يطلب من المتدربين دفع أي مبلغ، والتدريب مجاني"],
  ["summary", "ar", "يحصل المتدرب على مكافأة شهرية، ولا يدفع أي مبلغ"],
  ["summary", "ar", "على المتقدمين إرفاق السيرة الذاتية"],
  ["summary", "ar", "على المتقدم إحضار صورة الهوية"],
  ["needs", "ar", "يجب على المتقدم إتقان اللغة الإنجليزية"],
  ["summary", "ar", "يحذر من دفع أي مبلغ لأي شخص يدّعي أنه يمثل الشركة"],
  ["summary", "ar", "على المتقدمين الحذر من دفع أي مبلغ لمن يدّعي التوظيف"],
  ["summary", "ar", "لن يُطلب من المتقدمين، في أي مرحلة، دفع أي مبلغ"],
  ["summary", "ar", "انتبه: لا تدفع أي مبلغ لأي جهة تدعي أنها تمثلنا"],
  ["summary", "ar", "المتدرب لا يدفع أي مبلغ، والشركة تتحمل التكاليف"],
  ["summary", "ar", "على المتقدم عدم تسديد أي مبلغ لأي شخص"],
  ["summary", "ar", "التقديم مجاني ولا يتحمل المتقدم أي تكلفة"],
  ["summary", "ar", "لا يتوجب على المتقدم دفع أي مبلغ"],
  ["summary", "ar", "لا يُطلب من المتقدم في أي مرحلة دفع أي مبلغ"],
  ["summary", "ar", "يجب على المتقدمين عدم دفع أي مبلغ لأي وسيط"],
  ["summary", "ar", "ننوه إلى عدم دفع أي مبلغ من قبل المتقدمين"],
  ["summary", "ar", "ملاحظة هامة: لا يدفع المتدرب أي مبلغ مقابل التدريب"],
  ["summary", "ar", "المقابلة مجانية، فلا يدفع المتقدم أي مبلغ"],
  ["summary", "ar", "لا داعي لدفع أي مبلغ، فالتقديم مجاني"],
  ["summary", "ar", "بيئة عمل تحفز وتدفع المتدربين نحو التطور"],
  ["summary", "ar", "لا يدفع المتدربون أي مبلغ ولا يتحمل المتدرب أي تكاليف"],
  ["summary", "ar", "ولا يتحمل المتدرب أي تكاليف"],
  ["summary", "ar", "فلا يدفع المتدرب شيئاً"],
  ["summary", "ar", "لا يدفع المتقدم أي مبلغ، فالشركة تتحمل التكاليف كلها"],
  ["summary", "ar", "بيئة عمل تحفز وتدفع المتدربين نحو التطور"],
  ["summary", "ar", "برنامج تدريبي يحفز ويدفع المتدرب إلى الإبداع"],
  ["duties", "ar", "تنظيم الفواتير ويجب تسديد المبلغ المستحق للموردين"],
  ["duties", "ar", "متابعة الحسابات ويتعين تسديد مبلغ الضريبة في موعده"],
  ["provides", "en", "No fees or deposit required"],
  ["provides", "en", "You don't have to pay to apply."],
  ["provides", "en", "We will never ask you to pay to apply."],
  ["provides", "ar", "نرجو من المتقدمين عدم دفع أي مبلغ لأي جهة"],
  ["provides", "ar", "المطلوب عدم دفع رسوم لأي وسيط"]
];
const DEMANDS = [
  ["summary", "en", "Candidates must pay a 50,000 SYP registration fee"],
  ["provides", "en", "The trainee pays 100,000 SYP for the course"],
  ["provides", "en", "Applicants are required to pay 25 USD"],
  ["provides", "en", "Pay to apply: 10,000 SYP"],
  ["provides", "en", "Deposit required: 50 USD"],
  ["provides", "en", "You will need to pay 50 USD before starting"],
  ["provides", "en", "Pay a 50,000 SYP training fee before the interview"],
  ["provides", "en", "Interns pay 200 USD for the training kit"],
  ["provides", "en", "A refundable deposit of 100 USD is required"],
  ["provides", "en", "Each candidate pays 20,000 SYP for the exam"],
  ["provides", "en", "Trainees must pay for their own uniform"],
  ["provides", "en", "50,000 SYP must be paid on registration."],
  ["provides", "en", "Training costs 100 USD, paid by the trainee"],
  ["provides", "en", "Applicants will pay 30,000 SYP, refundable after 3 months"],
  ["provides", "en", "Successful candidates must pay 75 USD for medical tests"],
  ["provides", "en", "Every applicant pay 20,000 SYP registration"],
  ["provides", "en", "The candidate pay 50 USD for the training"],
  ["provides", "en", "It is required that each trainee pay 100,000 SYP"],
  ["provides", "en", "Note: trainees, pay 50 USD at the office"],
  ["summary", "ar", "على المتقدمين دفع رسوم تسجيل ٥٠ ألف ليرة"],
  ["provides", "ar", "يدفع المتدرب ١٠٠ ألف ليرة رسوم الدورة"],
  ["provides", "ar", "يتحمل المتدرب تكاليف الدورة التدريبية"],
  ["provides", "ar", "يجب تسديد ٥٠ ألف ليرة قبل المقابلة"],
  ["provides", "ar", "على المتقدم تسديد مبلغ ٢٥ ألف"],
  ["provides", "ar", "يلتزم المتدرب بدفع قسط شهري"],
  ["provides", "ar", "الإقامة على حساب المتدرب"],
  ["provides", "ar", "لا يشترط خبرة، يتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "مدة التدريب ثلاثة أشهر ويتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "المطلوب: دفع مبلغ ٥٠ ألف ليرة كتأمين"],
  ["provides", "ar", "يجب دفع: ٥٠ ألف ليرة"],
  ["provides", "ar", "يتحمل المتدرب: تكاليف الدورة التدريبية"],
  ["provides", "ar", "المتدرب يدفع ٥٠٬٠٠٠ ل.س"],
  ["provides", "ar", "يُطلب من المتقدمين دفع ٢٠ دولار"],
  ["provides", "ar", "بعد دفع رسوم التسجيل يبدأ التدريب"],
  ["provides", "ar", "وبعد دفع رسوم التسجيل يبدأ التدريب"],
  ["provides", "ar", "في حال عدم الالتزام بمدة العقد يدفع المتدرب تكاليف التدريب"],
  ["provides", "ar", "يتحمل المتقدم ثمن الزي الرسمي"],
  ["provides", "ar", "على المتدرب دفع اشتراك شهري، وهو ٢٠ ألف ليرة"],
  ["provides", "ar", "يدفع المتدرب، عند التسجيل، ٥٠ ألف ليرة"],
  ["provides", "ar", "لا يشترط خبرة ويتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "لا يشترط خبرة يتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "بدون خبرة يتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "السكن والطعام على حساب المتدرب"],
  ["provides", "ar", "السكن: على حساب المتدرب"],
  ["provides", "ar", "تكاليف المواصلات على نفقة المتدرب"],
  ["provides", "ar", "المتدرب يدفع: ٥٠ ألف ليرة"],
  ["provides", "ar", "يتوجب على المتدرب: دفع ٥٠ ألف ليرة"],
  ["provides", "ar", "المطلوب من المتقدم: دفع رسم التسجيل"],
  ["provides", "ar", "على المتقدم: تسديد ٢٠ ألف ليرة عند التسجيل"],
  ["provides", "ar", "يجب على المتقدم دفع ٢٥ دولار"],
  ["provides", "ar", "لا حاجة لخبرة، على المتقدم دفع ٢٥ دولار"],
  ["provides", "ar", "لا خبرة مطلوبة على المتقدم دفع ٢٥ دولار"],
  ["provides", "ar", "ولا يشترط خبرة وعلى المتدرب دفع ٢٥ دولار"],
  ["provides", "ar", "يتحمل المتدرب تكاليف السكن، والمواصلات"],
  ["provides", "ar", "تتحمل المتدربة تكاليف الدورة"],
  ["provides", "ar", "لا مانع من عدم الخبرة، ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "مع عدم وجود راتب ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "غير مدفوع ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "تدريب غير مأجور، ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "تدريب غير مأجور يتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "لا راتب والمتدرب يدفع ٥٠ الف"],
  ["summary", "ar", "في حال عدم الالتزام يتحمل المتدرب تكاليف التدريب"],
  ["summary", "ar", "مع عدم وجود راتب يتحمل المتدرب تكاليف التدريب"],
  ["summary", "ar", "في حال عدم الحضور يتحمل المتدرب تكاليف الدورة"],
  ["summary", "ar", "عند عدم إكمال التدريب يتحمل المتدرب تكاليف الدورة كاملة"],
  ["provides", "ar", "تكاليف الإعادة في حال عدم الحضور على حساب المتدرب"],
  ["summary", "ar", "شرط عدم الانسحاب يلتزم المتدرب بدفع قسط شهري"],
  ["summary", "ar", "يتحمل المتدرب: تكاليف الدورة والسكن والمواصلات"],
  ["needs", "ar", "يتحمل المتقدم: ثمن الزي الرسمي"],
  ["summary", "ar", "يتحمل المتدربون: تكاليف التدريب والسكن"],
  ["summary", "ar", "يتحمل المتدرب، تكاليف الدورة"],
  ["summary", "ar", "المطلوب: تسديد كفالة ١٠٠ ألف ليرة قبل البدء"],
  ["summary", "ar", "تكاليف الدورة ١٠٠ ألف"],
  ["summary", "ar", "رسم الدورة ١٠٠ ألف"],
  ["summary", "en", "Course fee: 100 euros, paid before the first session"],
  ["summary", "ar", "لا يشترط خبرة، يتحمل المتدرب تكاليف الدورة التدريبية"]
];

test("fee corpus: a legitimate listing line is never refused, in English or Arabic, whichever box it is in (107 lines)", () => {
  const bad = LEGIT.filter(x => outcome(x) === "refused");
  assert.deepEqual(bad, [], `refused: ${bad.map(x => x[2]).join(" | ")}`);
});

test("fee corpus: a demand that the candidate pay is refused or flagged for the reviewer, never silent (76 lines)", () => {
  const bad = DEMANDS.filter(x => outcome(x) === "silent");
  assert.deepEqual(bad, [], `silent: ${bad.map(x => x[2]).join(" | ")}`);
});

test("fee corpus: known residual, pinned so a fix flips it: in the listing's own text any fee word is refused, negated or not, as before Stage 4 (D-164)", () => {
  for (const x of [["duties", "en", "Collect cash payments from customers and deposit them at the bank daily"], ["summary", "en", "You never pay to apply on Shaghilni."]]) assert.equal(outcome(x), "refused", x[2]);
});
