/* The no-fees rule (R7, A-51) on a fixed corpus of realistic listing lines, gathered by the Stage 4 fix reviews: a legitimate line (stated pay, a benefit,
   a duty, an anti-scam or negated notice) is never refused, and a demand that the candidate pay is refused or at least flagged for the reviewer.
   A change to the fee wording that undoes an earlier round's case fails here (fix review 7). Add a line when a new case is found; never remove one. */
import { test } from "node:test";
import assert from "node:assert/strict";
import { loadCore } from "../server/core.js";
import { sanitizeJob, checkJob } from "../server/validate.js";

const core = loadCore(), base = { title: { en: "Storekeeper" }, gov: "aleppo", type: "full", level: "entry", pay: [1800000, 2200000], langs: ["ar"], summary: { en: "Keep the stock records." } };
const outcome = ([box, lang, line]) => { const r = checkJob(core, sanitizeJob(core, { ...base, [box]: box === "tags" ? line : box === "summary" || box === "place" ? { [lang]: line } : { [lang]: [line] } })); return r.fee ? "refused" : r.flags.some(f => f.type === "fee") ? "flagged" : "silent"; };   // tags is a string, place and summary one text, the rest lists

const LEGIT = [
  ["provides", "en", "Intern pay 400,000 SYP per month"],
  ["provides", "en", "Monthly stipend of 300,000 SYP for every trainee"],
  ["provides", "en", "Trainees are paid 250,000 SYP monthly"],
  ["provides", "en", "The company pays for transportation"],
  ["provides", "en", "We pay social insurance for all employees"],
  ["provides", "en", "Health insurance fully paid by the company"],
  ["provides", "en", "Tuition fees covered for further study"],
  ["provides", "en", "Paid annual leave of 14 days"],
  ["provides", "en", "Salary paid on the 1st of every month"],
  ["provides", "en", "Student pay 250,000 SYP per month"],
  ["provides", "en", "Interns will be paid 300,000 SYP"],
  ["provides", "en", "Transport allowance: 100,000 SYP"],
  ["provides", "en", "Students who complete the program will be paid a bonus of 200 USD"],
  ["provides", "en", "Free lunch, and we pay your internet bill"],
  ["provides", "en", "Trainee pay is 300,000 SYP, paid monthly"],
  ["provides", "en", "Each intern gets a 200 USD monthly allowance"],
  ["provides", "en", "We cover the trainee's transport; trainees pay nothing"],
  ["provides", "en", "Internship pay: 350,000 SYP; applicants pay nothing"],
  ["provides", "en", "Apprentice pay 300,000 SYP"],
  ["provides", "en", "Overtime is paid at 1.5x"],
  ["duties", "en", "Process customer payments and issue receipts"],
  ["duties", "en", "Pay suppliers on time and reconcile accounts"],
  ["duties", "en", "You will pay close attention to detail"],
  ["duties", "en", "Prepare payroll and pay employees' salaries"],
  ["duties", "en", "Handle the cash register and receive payments of up to 5 million SYP a day"],
  ["duties", "en", "Follow up on overdue invoices and make sure clients pay on time"],
  ["duties", "en", "Record student payments in the accounting system"],
  ["needs", "en", "Candidates must have 2 years of experience"],
  ["needs", "en", "Applicants should be able to work under pressure"],
  ["needs", "en", "The candidate will be paid according to experience"],
  ["provides", "en", "No candidate pays a fee"],
  ["provides", "en", "No deposit required"],
  ["provides", "en", "No applicant will pay a deposit"],
  ["summary", "en", "Applications are free. We will never ask you to pay anything."],
  ["summary", "en", "Candidates do not pay anything at any stage."],
  ["provides", "en", "No need to pay to apply"],
  ["provides", "en", "Candidates will never pay anything"],
  ["summary", "en", "Trainees will pay attention to safety rules at all times."],
  ["provides", "en", "Candidates never have to pay; beware of anyone asking for money"],
  ["provides", "ar", "مكافأة المتدرب تُدفع شهرياً"],
  ["provides", "ar", "مكافأة شهرية للمتدرب ٣٠٠ ألف ليرة"],
  ["provides", "ar", "تدفع الشركة بدل المواصلات"],
  ["provides", "ar", "تتحمل الشركة رسوم التسجيل في النقابة"],
  ["provides", "ar", "دفع رسوم النقابة على حساب الشركة"],
  ["provides", "ar", "تأمين صحي على حساب الشركة"],
  ["provides", "ar", "الراتب يُدفع في أول كل شهر"],
  ["provides", "ar", "يتم دفع الراتب ١٫٥ مليون ليرة شهرياً"],
  ["provides", "ar", "بدل مواصلات ١٠٠ ألف ليرة"],
  ["provides", "ar", "تدفع الشركة للمتدربين مكافأة ٢٠٠ ألف ليرة شهرياً"],
  ["summary", "ar", "يتقاضى المتدرب مكافأة شهرية قدرها ٢٠٠ ألف ليرة"],
  ["provides", "ar", "المتدرب يتقاضى ٣٠٠ ألف ليرة"],
  ["provides", "ar", "يُدفع للمتدرب ٤٠٠ ألف ليرة شهرياً"],
  ["provides", "ar", "مكافأة المتدرب تدفع ٤٠٠ ألف ليرة شهرياً"],
  ["provides", "ar", "مكافأة المتدرب: ٤٠٠ ألف ليرة، تدفع شهرياً"],
  ["provides", "ar", "نتكفل بدفع رسوم الدورات التدريبية"],
  ["provides", "ar", "فرصة تدريب مدفوعة الأجر"],
  ["provides", "ar", "وتدفع الشركة كامل تكاليف السكن"],
  ["provides", "ar", "وتتحمل الشركة تكاليف التدريب والسكن"],
  ["provides", "ar", "تدريب مدفوع، والشركة تتحمل التكاليف"],
  ["duties", "ar", "استلام الدفعات من الزبائن وتسجيلها"],
  ["duties", "ar", "تسديد فواتير الموردين ومتابعة الحسابات"],
  ["duties", "ar", "متابعة تحصيل المبالغ المستحقة من العملاء"],
  ["duties", "ar", "دفع رواتب الموظفين وإعداد كشوف الرواتب"],
  ["duties", "ar", "مسؤول عن تسديد الدفعات للموردين"],
  ["duties", "ar", "متابعة دفع الأقساط من الطلاب وتسجيلها"],
  ["duties", "ar", "تحصيل الأقساط من الطلاب وتسديدها للإدارة"],
  ["duties", "ar", "تدريب المتدربين ومتابعة أدائهم"],
  ["duties", "ar", "وتسديد الذمم المستحقة على الشركة"],
  ["summary", "ar", "التقديم مجاني ولا يدفع المتقدم أي مبلغ"],
  ["summary", "ar", "نرجو من المتقدمين عدم دفع أي مبلغ لأي جهة"],
  ["summary", "ar", "لا تطلب الشركة من المتقدمين دفع أي مبلغ"],
  ["summary", "ar", "تنبيه: الشركة لا تطلب من المتقدمين دفع أي مبلغ مقابل التوظيف"],
  ["summary", "ar", "التدريب مجاني بالكامل، ولا يتحمل المتدرب أي تكاليف"],
  ["summary", "ar", "ليس على المتقدم دفع أي مبلغ"],
  ["summary", "ar", "لا يطلب من المتدربين دفع أي مبلغ، والتدريب مجاني"],
  ["summary", "ar", "يحصل المتدرب على مكافأة شهرية، ولا يدفع أي مبلغ"],
  ["summary", "ar", "على المتقدمين إرفاق السيرة الذاتية"],
  ["summary", "ar", "على المتقدم إحضار صورة الهوية"],
  ["needs", "ar", "يجب على المتقدم إتقان اللغة الإنجليزية"],
  ["summary", "ar", "يحذر من دفع أي مبلغ لأي شخص يدّعي أنه يمثل الشركة"],
  ["summary", "ar", "على المتقدمين الحذر من دفع أي مبلغ لمن يدّعي التوظيف"],
  ["summary", "ar", "لن يُطلب من المتقدمين، في أي مرحلة، دفع أي مبلغ"],
  ["summary", "ar", "انتبه: لا تدفع أي مبلغ لأي جهة تدعي أنها تمثلنا"],
  ["summary", "ar", "المتدرب لا يدفع أي مبلغ، والشركة تتحمل التكاليف"],
  ["summary", "ar", "على المتقدم عدم تسديد أي مبلغ لأي شخص"],
  ["summary", "ar", "التقديم مجاني ولا يتحمل المتقدم أي تكلفة"],
  ["summary", "ar", "لا يتوجب على المتقدم دفع أي مبلغ"],
  ["summary", "ar", "لا يُطلب من المتقدم في أي مرحلة دفع أي مبلغ"],
  ["summary", "ar", "يجب على المتقدمين عدم دفع أي مبلغ لأي وسيط"],
  ["summary", "ar", "ننوه إلى عدم دفع أي مبلغ من قبل المتقدمين"],
  ["summary", "ar", "ملاحظة هامة: لا يدفع المتدرب أي مبلغ مقابل التدريب"],
  ["summary", "ar", "المقابلة مجانية، فلا يدفع المتقدم أي مبلغ"],
  ["summary", "ar", "لا داعي لدفع أي مبلغ، فالتقديم مجاني"],
  ["summary", "ar", "بيئة عمل تحفز وتدفع المتدربين نحو التطور"],
  ["summary", "ar", "لا يدفع المتدربون أي مبلغ ولا يتحمل المتدرب أي تكاليف"],
  ["summary", "ar", "ولا يتحمل المتدرب أي تكاليف"],
  ["summary", "ar", "فلا يدفع المتدرب شيئاً"],
  ["summary", "ar", "لا يدفع المتقدم أي مبلغ، فالشركة تتحمل التكاليف كلها"],
  ["summary", "ar", "بيئة عمل تحفز وتدفع المتدربين نحو التطور"],
  ["summary", "ar", "برنامج تدريبي يحفز ويدفع المتدرب إلى الإبداع"],
  ["duties", "ar", "تنظيم الفواتير ويجب تسديد المبلغ المستحق للموردين"],
  ["duties", "ar", "متابعة الحسابات ويتعين تسديد مبلغ الضريبة في موعده"],
  ["provides", "en", "No fees or deposit required"],
  ["provides", "en", "You don't have to pay to apply."],
  ["provides", "en", "We will never ask you to pay to apply."],
  ["provides", "ar", "نرجو من المتقدمين عدم دفع أي مبلغ لأي جهة"],
  ["provides", "ar", "المطلوب عدم دفع رسوم لأي وسيط"],
  // a second, fresh set written by an independent checker after the seventh review, to catch tuning to the first set (fix review 7)
  ["provides", "en", "Transport allowance of 60,000 SYP a month, paid with the salary"],
  ["provides", "en", "The company pays for the ICDL course and the exam"],
  ["provides", "en", "Mobile line and internet package paid by the company"],
  ["provides", "en", "Hot lunch every day, paid for by the employer"],
  ["provides", "en", "Overtime and Friday shifts are paid at double rate"],
  ["provides", "en", "Trainees receive 250,000 SYP a month in cash at the end of each month"],
  ["provides", "en", "Interns are paid every Thursday"],
  ["provides", "en", "Free laptop for every trainee; nobody pays for equipment"],
  ["provides", "en", "Health insurance for you and your family, paid in full by us"],
  ["provides", "en", "We pay half of your university tuition after one year of service"],
  ["provides", "en", "End-of-year bonus paid in December"],
  ["provides", "en", "Courses are not paid by the trainee; the company covers them"],
  ["provides", "en", "No intern will pay for training, uniforms or transport"],
  ["provides", "en", "Interns do not pay for their uniforms: the company provides them"],
  ["provides", "en", "Candidates will not have to pay anything at any stage"],
  ["provides", "en", "Training is free of charge and trainees never pay a deposit"],
  ["provides", "en", "Uniform paid by the company, not by the trainee"],
  ["provides", "en", "Phone credit of 25,000 SYP a month"],
  ["provides", "en", "Students who finish the internship will be paid a bonus"],
  ["provides", "en", "We cover exam fees for any certificate the trainee pursues"],
  ["provides", "en", "If you stay for a year, we pay for your master's degree"],
  ["provides", "en", "Participants pay €0: the programme is fully funded by the EU grant"],
  ["provides", "en", "Salary transferred to your bank account, or paid in cash if you prefer"],
  ["provides", "en", "Paid sick leave and 21 days of paid annual leave"],
  ["provides", "en", "Accommodation in Latakia paid by the company for staff from other governorates"],
  ["provides", "en", "The trainee never pays anything; the NGO covers transport and meals"],
  ["provides", "en", "Apprentices are paid 200,000 SYP from the first month"],
  ["provides", "en", "Daily meal allowance of 15,000 SYP for field days"],
  ["provides", "en", "Free Syriatel line with 50 GB a month"],
  ["provides", "en", "Your social insurance is paid by the company from day one"],
  ["provides", "en", "Trainees don't pay a penny, and you won't be asked to pay for the uniform"],
  ["provides", "en", "No trainee should pay anything to anyone claiming to represent us"],
  ["summary", "en", "Applying is completely free and no candidate will ever be asked to pay."],
  ["summary", "en", "We never charge applicants. If anyone asks you to pay, report it to us."],
  ["summary", "en", "Beware of fake recruiters: our company never asks candidates for money."],
  ["summary", "en", "This is a paid internship: interns are paid 300,000 SYP per month and pay nothing to join."],
  ["summary", "en", "Our cashiers handle payments of up to 10 million SYP a day, so accuracy matters."],
  ["summary", "en", "You will pay suppliers, reconcile the bank account and prepare monthly reports."],
  ["summary", "en", "No experience needed, and the candidate pays nothing to apply."],
  ["summary", "en", "We are hiring a cashier for our Aleppo branch; you will receive customer payments and close the till."],
  ["summary", "en", "The training is not paid by the trainee but by the company."],
  ["summary", "en", "Applicants never pay anything to us or to any agent acting in our name."],
  ["summary", "en", "Interview and onboarding are free of charge for every candidate."],
  ["summary", "en", "We are a family pharmacy in Hama looking for a cashier who can handle cash and card payments."],
  ["summary", "en", "Shifts are 8 hours; you will not be asked to pay for training or uniforms."],
  ["summary", "en", "Without any cost to you, the intern will be paid 150 USD a month by the project."],
  ["duties", "en", "Collect monthly rent from tenants and record every payment"],
  ["duties", "en", "Pay the daily fuel invoices and keep the receipts"],
  ["duties", "en", "Receive customer payments at the cash desk and close the till each evening"],
  ["duties", "en", "Prepare the monthly payroll and pay staff salaries through the bank"],
  ["duties", "en", "Follow up with students who have not paid their course instalments"],
  ["duties", "en", "Make sure that clients pay their invoices within 30 days"],
  ["duties", "en", "Issue receipts when trainees pay for the optional evening course"],
  ["duties", "en", "Pay customs duties for incoming shipments and file the papers"],
  ["duties", "en", "Pay the electricity and water bills of the branch on time"],
  ["duties", "en", "Record supplier payments in the ledger, in SYP and USD"],
  ["duties", "en", "Train new interns and check their daily reports"],
  ["needs", "en", "Candidates must be available to start immediately"],
  ["needs", "en", "Applicants should have a valid driving licence"],
  ["needs", "en", "The candidate must pass a short practical test, at no cost"],
  ["needs", "en", "Trainees must pay close attention to hygiene rules"],
  ["needs", "en", "You should have worked as a cashier before; you will be handling cash"],
  ["needs", "en", "Applicants must be comfortable handling cash payments"],
  ["needs", "en", "Candidates should know electronic payment systems such as Syriatel Cash"],
  ["needs", "en", "Interns need to bring their university ID"],
  ["place", "en", "Damascus, Mazzeh, near the Syriatel payment office"],
  ["place", "en", "Homs, Al-Waer, next to the electricity bill office"],
  ["place", "en", "Aleppo, Al-Aziziyah, 3rd floor"],
  ["tags", "en", "paid internship, accounting, Damascus"],
  ["tags", "en", "stipend, fresh graduates, Homs"],
  ["tags", "en", "cashier, payments, Latakia"],
  ["tags", "en", "free training, no charges, Tartus"],
  ["provides", "ar", "مكافأة شهرية للمتدربين قدرها ٢٥٠ ألف ليرة تُصرف آخر كل شهر"],
  ["provides", "ar", "تتكفل الشركة بتكاليف المواصلات والوجبات"],
  ["provides", "ar", "تأمين صحي تدفعه الشركة بالكامل"],
  ["provides", "ar", "الشركة تدفع رسوم الامتحان عن المتدرب"],
  ["provides", "ar", "سكن مجاني للمتدربين القادمين من المحافظات"],
  ["provides", "ar", "بدل اتصالات ٥٠ ألف ليرة شهرياً"],
  ["provides", "ar", "إجازة سنوية مدفوعة ١٤ يوماً"],
  ["provides", "ar", "الرواتب تُسدد بالدولار أو بما يعادلها بالليرة السورية"],
  ["provides", "ar", "لا يتحمّل المتدرب أيّ تكاليف، فالشركة تغطي كل شيء"],
  ["provides", "ar", "الزي الرسمي مجاني ولا يدفع المتدرب ثمنه"],
  ["provides", "ar", "السكن على حساب الشركة وليس على حساب المتدرب"],
  ["provides", "ar", "الإقامة ليست على نفقة المتدرب"],
  ["provides", "ar", "المواصلات مؤمنة ولا تكون على حساب المتدرب"],
  ["provides", "ar", "الوجبات ليست أبداً على حساب المتدرب"],
  ["provides", "ar", "الشركة تتحمل كل التكاليف، لا شيء على حساب المتدرب"],
  ["provides", "ar", "يُصرف للمتدرب بدل طعام يُدفع نقداً"],
  ["provides", "ar", "تدفع الشركة اشتراك النادي الرياضي للموظفين"],
  ["provides", "ar", "لا يتعين على المتدربين دفع ثمن الزي، فالشركة تؤمنه"],
  ["provides", "ar", "مكافأة المتدربين تُدفع ٣٠٠ ألف ليرة شهرياً"],
  ["provides", "ar", "تتحمل الشركة نفقات السفر والإقامة للمتدربين"],
  ["provides", "ar", "خط سيريتل مجاني مع باقة إنترنت تدفعها الشركة"],
  ["provides", "ar", "تعويض نهاية خدمة حسب قانون العمل"],
  ["provides", "ar", "لا تكون تكاليف الدورة على حساب المتدرب بأي حال"],
  ["provides", "ar", "يتقاضى المتدرب ٢٠٠ ألف ليرة، ولا يتحمل أي تكاليف"],
  ["provides", "ar", "التدريب والسكن ليسا على حساب المتدرب"],
  ["provides", "ar", "الكتب مجانية ولن تكون على نفقة المتدرب"],
  ["summary", "ar", "التقديم مجاني، ولن يكون على المتقدم دفع أي مبلغ في أي مرحلة"],
  ["summary", "ar", "ليس مطلوباً من المتدرب دفع أي مبلغ"],
  ["summary", "ar", "لا داعي أن يدفع المتقدم أي مبلغ، فالتقديم مجاني"],
  ["summary", "ar", "التدريب مجاني دون أن يُطلب من المتدرب دفع أي مبلغ"],
  ["summary", "ar", "نحن لا نطلب أبداً من المتقدمين دفع أي مبلغ"],
  ["summary", "ar", "لا يُشترط أن يدفع المرشح أي مبلغ للحصول على الوظيفة"],
  ["summary", "ar", "لا يُفرض على المتدرب دفع أي مبلغ مقابل التدريب"],
  ["summary", "ar", "ما في داعي يدفع المتقدم ولا ليرة، التقديم ببلاش"],
  ["summary", "ar", "لا يُطلب إطلاقاً من المتقدمين دفع أي مبلغ"],
  ["summary", "ar", "تحذير: لا تطلب الشركة ولا موظفوها من المتقدمين دفع أي مبلغ"],
  ["summary", "ar", "لن يُطلب منك دفع أي مبلغ مقابل التوظيف"],
  ["summary", "ar", "الشركة لا تأخذ أي عمولة، ولا يدفع المرشح شيئاً"],
  ["summary", "ar", "ملاحظة: لا يُطلب من المتقدمين أو المتدربين دفع أي مبلغ"],
  ["summary", "ar", "يتقاضى المتدربون مكافأة، وتدفع الشركة تكاليف الدورة"],
  ["summary", "ar", "رواتب المتدربين تُسدد في الخامس من كل شهر"],
  ["summary", "ar", "المتقدم غير مطالب بدفع أي مبلغ"],
  ["summary", "ar", "لا يتوجب على المتقدم بأي حال دفع أي مبلغ"],
  ["summary", "ar", "لم يُطلب ولن يُطلب من المتقدمين دفع أي مبلغ"],
  ["summary", "ar", "نود التنويه أنه لا يتوجب على المتدرب دفع أي مبلغ"],
  ["summary", "ar", "ليس على المتقدمين أن يدفعوا أي مبلغ"],
  ["summary", "ar", "التدريب مجاني، فلا يتحمل المتدرب أي تكلفة"],
  ["summary", "ar", "برنامج يدفع المتدربين نحو سوق العمل"],
  ["summary", "ar", "فرصة تدفع المتدرب الى الأمام"],
  ["summary", "ar", "لا يُطلب أبداً من المتدرب دفع أي مبلغ، والتدريب ممول بالكامل"],
  ["summary", "ar", "لا تفرض الشركة على المتقدمين دفع أي مبلغ"],
  ["summary", "ar", "لم يعد على المتدربين دفع أي مبلغ بعد تمويل البرنامج"],
  ["duties", "ar", "استلام الدفعات النقدية من الزبائن وإيداعها في البنك"],
  ["duties", "ar", "تسديد فواتير الكهرباء والماء والهاتف شهرياً"],
  ["duties", "ar", "الإشراف على المتدربين، تسديد الفواتير، ومتابعة الحسابات"],
  ["duties", "ar", "الإشراف على المتدربين الجدد، دفع رواتب العمال، وتنظيم الدوام"],
  ["duties", "ar", "تحصيل الأقساط من المتدربين، تسديد مستحقات المدربين"],
  ["duties", "ar", "استلام العروض من المتقدمين للمناقصة، سداد مستحقات الموردين"],
  ["duties", "ar", "دفع مكافآت المتدربين في موعدها"],
  ["duties", "ar", "مراجعة قسائم الرواتب قبل الدفع"],
  ["duties", "ar", "يجب تسديد الضرائب المستحقة في موعدها"],
  ["duties", "ar", "متابعة المتدربين، تسديد الدفعات للموردين، وإعداد التقارير"],
  ["duties", "ar", "توزيع المهام على المتدربين، سداد فواتير الموردين"],
  ["duties", "ar", "استقبال الطلبات من المرشحين، دفع الرواتب، والأرشفة"],
  ["duties", "ar", "إعداد كشوف الرواتب وتسديد التأمينات الاجتماعية"],
  ["duties", "ar", "قبض ثمن المبيعات من الزبائن وتسليمه للمحاسب"],
  ["duties", "ar", "تدريب المتدربين: دفع العمل اليومي وتوزيع المهام"],
  ["needs", "ar", "على المتقدم أن يكون ملماً بأنظمة الدفع الإلكتروني"],
  ["needs", "ar", "يجب على المتقدمين إتقان برامج المحاسبة وأنظمة الدفع"],
  ["needs", "ar", "خبرة في تحصيل الأقساط من المتدربين"],
  ["needs", "ar", "على المرشح الالتزام بالدوام الكامل"],
  ["needs", "ar", "خبرة لا تقل عن سنتين في تسديد ومتابعة الذمم"],
  ["needs", "ar", "يُشترط: خبرة في دفع الرواتب عبر البنوك"],
  ["needs", "ar", "القدرة على التعامل مع المتقدمين، دفع العمل بروح الفريق"],
  ["place", "ar", "دمشق، المزة، قرب مديرية المالية"],
  ["place", "ar", "حلب - العزيزية، مقابل مكتب تسديد الفواتير"],
  ["place", "ar", "حمص، شارع الدبلان، فوق محل الصرافة"],
  ["tags", "ar", "تدريب مدفوع، محاسبة، حمص"],
  ["tags", "ar", "براتب، بدون خبرة، طلاب جامعة"],
  ["tags", "ar", "كاشير، تحصيل، دفع إلكتروني"],
  ["tags", "ar", "تدريب للمتدربين، دفع رواتب، محاسبة"]
];
const DEMANDS = [
  ["summary", "en", "Candidates must pay a 50,000 SYP registration fee"],
  ["provides", "en", "The trainee pays 100,000 SYP for the course"],
  ["provides", "en", "Applicants are required to pay 25 USD"],
  ["provides", "en", "Pay to apply: 10,000 SYP"],
  ["provides", "en", "Deposit required: 50 USD"],
  ["provides", "en", "You will need to pay 50 USD before starting"],
  ["provides", "en", "Pay a 50,000 SYP training fee before the interview"],
  ["provides", "en", "Interns pay 200 USD for the training kit"],
  ["provides", "en", "A refundable deposit of 100 USD is required"],
  ["provides", "en", "Each candidate pays 20,000 SYP for the exam"],
  ["provides", "en", "Trainees must pay for their own uniform"],
  ["provides", "en", "50,000 SYP must be paid on registration."],
  ["provides", "en", "Training costs 100 USD, paid by the trainee"],
  ["provides", "en", "Applicants will pay 30,000 SYP, refundable after 3 months"],
  ["provides", "en", "Successful candidates must pay 75 USD for medical tests"],
  ["provides", "en", "Every applicant pay 20,000 SYP registration"],
  ["provides", "en", "The candidate pay 50 USD for the training"],
  ["provides", "en", "It is required that each trainee pay 100,000 SYP"],
  ["provides", "en", "Note: trainees, pay 50 USD at the office"],
  ["summary", "ar", "على المتقدمين دفع رسوم تسجيل ٥٠ ألف ليرة"],
  ["provides", "ar", "يدفع المتدرب ١٠٠ ألف ليرة رسوم الدورة"],
  ["provides", "ar", "يتحمل المتدرب تكاليف الدورة التدريبية"],
  ["provides", "ar", "يجب تسديد ٥٠ ألف ليرة قبل المقابلة"],
  ["provides", "ar", "على المتقدم تسديد مبلغ ٢٥ ألف"],
  ["provides", "ar", "يلتزم المتدرب بدفع قسط شهري"],
  ["provides", "ar", "الإقامة على حساب المتدرب"],
  ["provides", "ar", "لا يشترط خبرة، يتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "مدة التدريب ثلاثة أشهر ويتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "المطلوب: دفع مبلغ ٥٠ ألف ليرة كتأمين"],
  ["provides", "ar", "يجب دفع: ٥٠ ألف ليرة"],
  ["provides", "ar", "يتحمل المتدرب: تكاليف الدورة التدريبية"],
  ["provides", "ar", "المتدرب يدفع ٥٠٬٠٠٠ ل.س"],
  ["provides", "ar", "يُطلب من المتقدمين دفع ٢٠ دولار"],
  ["provides", "ar", "بعد دفع رسوم التسجيل يبدأ التدريب"],
  ["provides", "ar", "وبعد دفع رسوم التسجيل يبدأ التدريب"],
  ["provides", "ar", "في حال عدم الالتزام بمدة العقد يدفع المتدرب تكاليف التدريب"],
  ["provides", "ar", "يتحمل المتقدم ثمن الزي الرسمي"],
  ["provides", "ar", "على المتدرب دفع اشتراك شهري، وهو ٢٠ ألف ليرة"],
  ["provides", "ar", "يدفع المتدرب، عند التسجيل، ٥٠ ألف ليرة"],
  ["provides", "ar", "لا يشترط خبرة ويتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "لا يشترط خبرة يتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "بدون خبرة يتحمل المتدرب تكاليف الدورة"],
  ["provides", "ar", "السكن والطعام على حساب المتدرب"],
  ["provides", "ar", "السكن: على حساب المتدرب"],
  ["provides", "ar", "تكاليف المواصلات على نفقة المتدرب"],
  ["provides", "ar", "المتدرب يدفع: ٥٠ ألف ليرة"],
  ["provides", "ar", "يتوجب على المتدرب: دفع ٥٠ ألف ليرة"],
  ["provides", "ar", "المطلوب من المتقدم: دفع رسم التسجيل"],
  ["provides", "ar", "على المتقدم: تسديد ٢٠ ألف ليرة عند التسجيل"],
  ["provides", "ar", "يجب على المتقدم دفع ٢٥ دولار"],
  ["provides", "ar", "لا حاجة لخبرة، على المتقدم دفع ٢٥ دولار"],
  ["provides", "ar", "لا خبرة مطلوبة على المتقدم دفع ٢٥ دولار"],
  ["provides", "ar", "ولا يشترط خبرة وعلى المتدرب دفع ٢٥ دولار"],
  ["provides", "ar", "يتحمل المتدرب تكاليف السكن، والمواصلات"],
  ["provides", "ar", "تتحمل المتدربة تكاليف الدورة"],
  ["provides", "ar", "لا مانع من عدم الخبرة، ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "مع عدم وجود راتب ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "غير مدفوع ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "تدريب غير مأجور، ويتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "تدريب غير مأجور يتحمل المتدرب تكاليف التدريب"],
  ["provides", "ar", "لا راتب والمتدرب يدفع ٥٠ الف"],
  ["summary", "ar", "في حال عدم الالتزام يتحمل المتدرب تكاليف التدريب"],
  ["summary", "ar", "مع عدم وجود راتب يتحمل المتدرب تكاليف التدريب"],
  ["summary", "ar", "في حال عدم الحضور يتحمل المتدرب تكاليف الدورة"],
  ["summary", "ar", "عند عدم إكمال التدريب يتحمل المتدرب تكاليف الدورة كاملة"],
  ["provides", "ar", "تكاليف الإعادة في حال عدم الحضور على حساب المتدرب"],
  ["summary", "ar", "شرط عدم الانسحاب يلتزم المتدرب بدفع قسط شهري"],
  ["summary", "ar", "يتحمل المتدرب: تكاليف الدورة والسكن والمواصلات"],
  ["needs", "ar", "يتحمل المتقدم: ثمن الزي الرسمي"],
  ["summary", "ar", "يتحمل المتدربون: تكاليف التدريب والسكن"],
  ["summary", "ar", "يتحمل المتدرب، تكاليف الدورة"],
  ["summary", "ar", "المطلوب: تسديد كفالة ١٠٠ ألف ليرة قبل البدء"],
  ["summary", "ar", "تكاليف الدورة ١٠٠ ألف"],
  ["summary", "ar", "رسم الدورة ١٠٠ ألف"],
  ["summary", "en", "Course fee: 100 euros, paid before the first session"],
  ["summary", "ar", "لا يشترط خبرة، يتحمل المتدرب تكاليف الدورة التدريبية"],
  // the checker's fresh set
  ["provides", "en", "Housing is not included and is paid by the trainee"],
  ["provides", "en", "Transport is not provided and must be paid by the trainee"],
  ["provides", "en", "There is no stipend and the training is paid by the participants"],
  ["provides", "en", "The trainee pays 75 USD for the ICDL exam"],
  ["provides", "en", "Applicants are expected to pay 15,000 SYP for the application file"],
  ["provides", "en", "You must pay 30,000 SYP to reserve your place"],
  ["provides", "en", "Not covered by the company: the exam, paid by the applicant"],
  ["provides", "en", "Without a scholarship, the programme is paid by the student"],
  ["provides", "en", "Candidates who do not live in Damascus will pay 50 USD for the dormitory"],
  ["provides", "en", "If you fail the test you will pay 20 USD for a retake"],
  ["provides", "en", "If you do not attend all sessions you will pay 100 USD"],
  ["provides", "en", "Interns who don't finish the programme must pay back 200 USD"],
  ["provides", "en", "Each participant pays 10 USD for materials"],
  ["provides", "en", "Applicants should pay the 5,000 SYP file cost when they come for the interview"],
  ["provides", "en", "Training is not free: every trainee pays 150 USD"],
  ["provides", "en", "Training is not free and every trainee pays 150 USD"],
  ["provides", "en", "Uniforms are not free, paid by the candidate"],
  ["provides", "en", "Trainees without a laptop will pay 300 USD for one"],
  ["provides", "en", "Unpaid, and the certificate is paid by the intern"],
  ["provides", "en", "No accommodation is offered and rent is paid by the intern"],
  ["provides", "en", "Medical check not included and paid by the candidate"],
  ["provides", "en", "Trainees must cover the cost of their own safety boots"],
  ["provides", "en", "Interns will pay 25 euros for the certificate"],
  ["provides", "en", "The student pays €40 for the workbook"],
  ["provides", "en", "Successful applicants pay 100,000 SYP before signing the contract"],
  ["provides", "en", "Note: the trainee will have to pay 50 USD for insurance"],
  ["provides", "en", "Exam not included and paid by the candidate, 20 USD"],
  ["provides", "en", "Lunch is not free and is paid by the trainees"],
  ["summary", "en", "Accepted trainees pay a one-time 100 USD registration amount."],
  ["summary", "en", "No salary is offered and the course materials are paid by the intern."],
  ["summary", "en", "To confirm your seat you must pay 50,000 SYP in advance."],
  ["summary", "en", "Food is not provided and is paid by the trainees themselves."],
  ["summary", "en", "No experience needed and the uniform is paid by the trainee."],
  ["summary", "en", "Experience not required and the course book is paid by the student."],
  ["summary", "en", "This is not a paid internship; candidates must pay 50 USD for supervision."],
  ["summary", "en", "This is not a paid internship and candidates must pay 50 USD for supervision."],
  ["summary", "en", "We do not provide transport, so it is paid by the trainee."],
  ["needs", "en", "Laptop not provided; trainees pay for their own"],
  ["needs", "en", "The candidate must pay for the medical test"],
  ["needs", "en", "Applicants need to pay 10 USD for the language test"],
  ["needs", "en", "Smart phone not supplied and paid by the applicant"],
  ["tags", "en", "trainees must pay 20000 SYP"],
  ["tags", "en", "course paid by the trainee"],
  ["tags", "en", "no salary, paid by the trainee"],
  ["tags", "en", "no salary and paid by the trainee"],
  ["place", "en", "Pay 10 USD at reception before the interview"],
  ["place", "en", "Training centre, Homs; trainees pay 25 USD at the door"],
  ["provides", "ar", "تكاليف الدورة يدفعها المتدرب على دفعتين"],
  ["provides", "ar", "أجرة السكن يدفعها المتدرب إلى صاحب البيت مباشرة"],
  ["provides", "ar", "أما المواصلات فيدفعها المتدرب"],
  ["provides", "ar", "السكن متوفر وتدفعه المتدربة"],
  ["provides", "ar", "ثمن الكتب والقرطاسية يدفعه المتدرب"],
  ["provides", "ar", "يتحمل المتدرب نفقات السفر والإقامة"],
  ["provides", "ar", "على المتقدمين سداد ٢٠ ألف ليرة بدل فتح ملف"],
  ["provides", "ar", "على كل متقدم دفع ١٠ دولارات"],
  ["provides", "ar", "المتدرب يسدد ثمن الزي"],
  ["provides", "ar", "تتحمل المتقدمة تكاليف الفحص الطبي"],
  ["provides", "ar", "تكلفة الفحص الطبي على نفقة المرشح"],
  ["provides", "ar", "المطلوب دفع ٢٥ ألف ليرة لتثبيت الحجز"],
  ["provides", "ar", "يشترط تسديد مبلغ ١٠٠ دولار كتأمين قبل استلام العمل"],
  ["provides", "ar", "من لا يسكن في دمشق تكون الإقامة على حساب المتدرب"],
  ["provides", "ar", "الدورة غير مجانية ويدفع المتدرب ١٠٠ دولار"],
  ["provides", "ar", "الدورة غير مجانية، يدفع المتدرب ١٠٠ دولار"],
  ["provides", "ar", "غير شامل السكن: يتحمله المتدرب"],
  ["provides", "ar", "تذكرة السفر غير مشمولة وتكون على حساب المتدرب"],
  ["provides", "ar", "المواصلات ليست مؤمنة وهي على نفقة المتدرب"],
  ["provides", "ar", "وتدفعها المتدربة نقداً عند التسجيل"],
  ["provides", "ar", "الزي الرسمي يسدده المتدرب"],
  ["provides", "ar", "يدفع كل متدرب ٢٠ دولار عند التسجيل"],
  ["provides", "ar", "لا يوجد راتب، ويدفع المتدرب تكاليف التدريب"],
  ["provides", "ar", "التدريب بدون راتب، والمتدرب يدفع ثمن الكتب"],
  ["provides", "ar", "لا يوجد راتب، المتدرب يدفع ١٠٠ ألف ليرة"],
  ["provides", "ar", "تكاليف الامتحان تدفعها المتقدمة إلى المعهد"],
  ["provides", "ar", "لا راتب، أما السكن فيدفعه المتدرب"],
  ["provides", "ar", "السكن والمواصلات يدفعها المتدربون على حسابهم"],
  ["provides", "ar", "مصاريف الإقامة يتحملها المتدرب"],
  ["provides", "ar", "يتكفل المتدرب بمصاريف التدريب"],
  ["provides", "ar", "الكتب على حساب المتدرب، والسكن مجاني"],
  ["provides", "ar", "ثمن الحقيبة التدريبية تدفعه المتدربة عند أول يوم"],
  ["provides", "ar", "تكاليف الشهادة يدفعها المتقدم الى إدارة المعهد"],
  ["provides", "ar", "أجور المواصلات فيدفعها المتدربون بأنفسهم"],
  ["provides", "ar", "التدريب غير مأجور وتسدد المتدربة ٥٠ ألف ليرة"],
  ["summary", "ar", "يدفع المتدرب قسطاً شهرياً قدره ٥٠ ألف ليرة"],
  ["summary", "ar", "يلتزم المتدربون بدفع أجور السكن"],
  ["summary", "ar", "يتوجب على المتدرب تسديد كلفة الدورة قبل بدايتها"],
  ["summary", "ar", "في حال الانسحاب قبل انتهاء العقد يدفع المتدرب ٣٠٠ دولار"],
  ["summary", "ar", "في حال عدم إكمال الدورة يدفع المتدرب كامل التكاليف"],
  ["summary", "ar", "إذا لم يحضر المتدرب الامتحان يدفع ٢٠ ألف ليرة"],
  ["summary", "ar", "إذا لم يلتزم المتدرب بالدوام يتحمل المتدرب تكاليف التدريب"],
  ["summary", "ar", "لمن لا يملك حاسوباً، يتحمل المتدرب ثمن الجهاز"],
  ["summary", "ar", "لمن لا يملك حاسوباً يتحمل المتدرب ثمن الجهاز"],
  ["summary", "ar", "على المتدربين: دفع ٢٥ ألف ليرة بدل مواد"],
  ["summary", "ar", "تكاليف الكتب: على حساب المتدرب"],
  ["summary", "ar", "يتحمل المرشحون، عند القبول، تكاليف الفحص الطبي"],
  ["summary", "ar", "المتدرب بيدفع ٥٠ ألف أول شهر"],
  ["summary", "ar", "لازم يدفع المتدرب حق الدورة"],
  ["summary", "ar", "لا يُقبل أي متقدم ما لم يدفع ٥٠ ألف ليرة"],
  ["summary", "ar", "مطلوب متدربين، يدفع المتدرب ١٥ ألف ليرة شهرياً بدل إشراف"],
  ["summary", "ar", "بدون خبرة، فقط على المتقدم تسديد ٢٠ دولار"],
  ["summary", "ar", "التدريب لا يشمل الإقامة وتكاليفها يدفعها المتدرب"],
  ["summary", "ar", "الدورة لا تشمل الكتب ويدفع ثمنها المتدرب"],
  ["summary", "ar", "لا يوجد سكن، والمتدرب يتحمل تكاليفه"],
  ["summary", "ar", "في حال الغياب أكثر من ثلاثة أيام يتحمل المتدرب تكاليف الإعادة"],
  ["summary", "ar", "التدريب ليس مجانياً: يتحمل المتدرب تكاليف المواد"],
  ["summary", "ar", "التدريب ليس مجانياً ويتحمل المتدرب تكاليف المواد"],
  ["summary", "ar", "لا توجد مكافأة، وتكاليف الدورة يدفعها المتدرب على ثلاث مراحل"],
  ["needs", "ar", "يجب أن يدفع المتقدم ثمن الملف"],
  ["needs", "ar", "يُشترط أن يسدد المرشح مبلغ التأمين"],
  ["needs", "ar", "يجب على المتقدم دفع تأمين ٥٠ دولار عند التوقيع"],
  ["needs", "ar", "أن يتحمل المتقدم نفقات الفحص الطبي"],
  ["tags", "ar", "على المتدرب دفع اشتراك"],
  ["tags", "ar", "رسوم تسجيل ٢٠ ألف"],
  ["tags", "ar", "الكتب على نفقة المتدرب"],
  ["place", "ar", "الدفع عند التسجيل في المكتب"],
  ["place", "ar", "مكتب التسجيل: يدفع المتقدم ١٠ آلاف ليرة"]
];

test("fee corpus: a legitimate listing line is never refused, in English or Arabic, whichever box it is in (260 lines)", () => {
  const bad = LEGIT.filter(x => outcome(x) === "refused");
  assert.deepEqual(bad, [], `refused: ${bad.map(x => x[2]).join(" | ")}`);
});

test("fee corpus: a demand that the candidate pay is refused or flagged for the reviewer, never silent (191 lines)", () => {
  const bad = DEMANDS.filter(x => outcome(x) === "silent");
  assert.deepEqual(bad, [], `silent: ${bad.map(x => x[2]).join(" | ")}`);
});

test("fee corpus: known residual, pinned so a fix flips it: in the listing's own text any fee word is refused, negated or not, as before Stage 4 (D-164)", () => {
  for (const x of [["duties", "en", "Collect cash payments from customers and deposit them at the bank daily"], ["summary", "en", "You never pay to apply on Shaghilni."], ["duties", "en", "Count the cash, prepare the deposit slip and take it to the bank"],
    ["summary", "ar", "التقديم مجاني تماماً ولا يُطلب منكم دفع مبلغ"], ["summary", "ar", "انتبه، لا أحد في الشركة يطلب من المتقدم دفع مبلغ"], ["summary", "ar", "لا يجوز لأي موظف أن يطلب من المتقدم دفع أي مبلغ"], ["summary", "ar", "لن يُطلب في أي وقت من المتقدم دفع مبلغ"]]) assert.equal(outcome(x), "refused", x[2]);
});
